defaults:
  - common: default_setup
  - _self_

model_name: "ensemble_user_ratio"

data:
  data_dir: "~/data/raw/train/"
  data_file: "train_ratings.csv"
  min_interactions: 3
  seed: 42
  num_workers: 4

model:
  max_len: 50   # BERT 입력용

ensemble:
  bert_model_name: "bert4rec"
  ease_model_name: "ease"
  bert_topk: 5     # BERT에서 최대 몇 개 뽑을지

inference:
  topk: 10
  batch_size: 256
